version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Exp Login
          command: cat <(echo login; exp login --username $EXPO_USER --password $EXPO_PASS)

      - run:
          name: Exp Publish
          command: cat <(echo publish; exp publish)

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
